//Modal Action Types
export const OPEN_WARNING_MODAL = "OPEN_WARNING_MODAL";

// Loader Action Types
export const SHOW_LOADER = "SHOW_LOADER";

// User Action Types
export const USERS_REGISTER_REQUEST = "USERS_REGISTER_REQUEST";
export const USERS_LOGIN_REQUEST = "USERS_LOGIN_REQUEST";
export const USERS_LOGOUT = "USERS_LOGOUT";

//Application Action Types
export const APPLICATION_CREATE_REQUEST = "APPLICATION_CREATE_REQUEST";
export const APPLICATION_GET_REQUEST = "APPLICATION_GET_REQUEST";
export const APPLICATION_GET_REQUEST_BY_ID = "APPLICATION_GET_REQUEST_BY_ID";
export const OBJECT_GET_REQUEST_BY_APPLICATION_ID = "OBJECT_GET_REQUEST_BY_APPLICATION_ID";

// Object Action Types
export const OBJECT_GET_REQUEST = "OBJECT_GET_REQUEST";
export const OBJECT_GET_REQUEST_BY_ID = "OBJECT_GET_REQUEST_BY_ID";
export const OBJECT_CREATE_REQUEST = "OBJECT_CREATE_REQUEST";
export const OBJECT_DELETE_REQUEST_BY_ID = "OBJECT_DELETE_REQUEST_BY_ID";
export const FIELDS_GET_REQUEST_BY_OBJECT_ID = "FIELDS_GET_REQUEST_BY_OBJECT_ID";

// Record Action Types
export const RECORDS_GET_REQUEST = "RECORDS_GET_REQUEST";
export const RECORD_GET_REQUEST_BY_ID = "RECORD_GET_REQUEST_BY_ID";
export const RECORD_CREATE_REQUEST = "RECORD_CREATE_REQUEST";
export const RECORD_DELETE_REQUEST_BY_ID = "RECORD_DELETE_REQUEST_BY_ID";
export const RECORD_GET_REQUEST_BY_OBJECT_ID = "RECORD_GET_REQUEST_BY_OBJECT_ID";
export const GET_RELATED_LIST_BY_RECORD_ID = "GET_RELATED_LIST_BY_RECORD_ID";
// Layout Action Types
export const SIDEBAR_GET_REQUEST = "SIDEBAR_GET_REQUEST";


//Fields Action Types
export const FIELD_CREATE_REQUEST = "FIELD_CREATE_REQUEST";
export const FIELD_GET_REQUEST = "FIELD_GET_REQUEST";
export const FIELD_GET_REQUEST_BY_ID = "FIELD_GET_REQUEST_BY_ID";



//Common Action Types
export const LOOKUP_GET_REQUEST = "LOOKUP_GET_REQUEST";
