export const fieldTypeOptions = [
  { value: "text", label: "Text", color: "#f0f" },
  { value: "email", label: "Email" },
  { value: "dropdown", label: "Dropdown" },
  { value: "phone", label: "Phone" },
  { value: "password", label: "Password" },
  { value: "textarea", label: "Textarea" },
  { value: "Textarea(Rich)", label: "Textarea(Rich)" },
  { value: "autoNumber", label: "Auto Number" },
  { value: "checkbox", label: "Checkbox" },
  { value: "date", label: "Date" },
  { value: "dateTime", label: "Date & Time" },
  { value: "email", label: "Email" },
  { value: "number", label: "Number" },
  { value: "percent", label: "Percent" },
  { value: "phone", label: "Phone" },
  { value: "dropdown", label: "Dropdown" },
  { value: "dropdownMultiSelect", label: "Dropdown MultiSelect" },
  { value: "time", label: "Time" },
  { value: "url", label: "URL" },
  { value: "colorCoding", label: "Color Coding" },
  { value: "progressBar", label: "Progress Bar" },
  { value: "duration", label: "Duration" }
]